MODEL:
  META_ARCHITECTURE: "DispRCNN3D"
  POINTRCNN:
    MASK_THRESH: 0.5
    AUG_DATA: True
    MEAN_SIZE: [[ 1.76070649, 0.66018944, 0.84228438]]
    RPN:
      LOSS_CLS: BinaryCrossEntropy
      SA_CONFIG:
        NPOINTS: [768, 512, 256, 64]
  MASK_ON: True
  STEREO_ON: True
  DET3D_ON: True
  DISPNET_ON: False
DATASETS:
  TRAIN: ("kitti_train_vob_pedestrian", )
  TEST: ("kitti_val_vob_pedestrian",)
DATALOADER:
  SIZE_DIVISIBILITY: 1
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  SCHEDULER: OneCycleScheduler
  MAX_ITER: 27600
  IMS_PER_BATCH: 3
  TRAIN_PSM: False
  TRAIN_PC: True
  LOAD_OPTIMIZER: False
  LOAD_SCHEDULER: False
  FIX_DISPARITY: True
  PRINT_INTERVAL: 1
  PRINT_ITERATION: False
  ALLOW_EXCEPTION: True
  DO_GRAD_CLIP: True
  REMOVE_EMPTY_ANNOTATIONS_TRAIN: False
  OFFLINE_2D_PREDICTIONS: "models/kitti/pedestrian/vob/idispnet/inference/kitti_%s_vob_pedestrian/predictions"
  CHECKPOINT_PERIOD: 138
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR:
  "models/kitti/pedestrian/vob/rpn"
INPUT:
  DO_RESIZE: False
  FLIP_PROB_TRAIN: 0.0
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 10000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 10000
  PIXEL_MEAN: [0.0, 0.0, 0.0]
  PIXEL_STD: [1.0, 1.0, 1.0]
  TO_BGR255: False