MODEL:
  META_ARCHITECTURE: "DispRCNN3D"
  DISPNET:
    MAX_DISP: 48
    MIN_DISP: -48
    RESOLUTIONS: (224,)
    LOSS_WEIGHT: 0.05
    MAX_ROI_FOR_TRAINING: 12
    ROI_MIN_SCORE: 0.5
    TRAINED_MODEL: "models/kitti/car/pob/idispnet/bestmodel.pth"
  POINTRCNN:
    MEAN_SIZE: [[1.52563191462, 1.62856739989, 3.88311640418]]
    RPN:
      LOSS_CLS: BinaryCrossEntropy
  MASK_ON: True
  STEREO_ON: True
  DET3D_ON: False
DATASETS:
  TRAIN: ("kitti_train_pob_car", )
  TEST: ("kitti_train_pob_car", "kitti_val_pob_car")
DATALOADER:
  SIZE_DIVISIBILITY: 1
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  SCHEDULER: OneCycleScheduler
  MAX_ITER: 41000
  IMS_PER_BATCH: 2
  TRAIN_PSM: True
  TRAIN_PC: False
  LOAD_OPTIMIZER: False
  LOAD_SCHEDULER: False
  PRINT_INTERVAL: 1
  PRINT_ITERATION: False
  REMOVE_EMPTY_ANNOTATIONS_TRAIN: False
  OFFLINE_2D_PREDICTIONS: "models/kitti/car/pob/mask/inference/kitti_%s_pob_car/predictions"
  CHECKPOINT_PERIOD: 410
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR:
  "models/kitti/car/pob/idispnet"
INPUT:
  FLIP_PROB_TRAIN: 0.0
  DO_RESIZE: False
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 10000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 10000
  PIXEL_MEAN: [0.0, 0.0, 0.0]
  PIXEL_STD: [1.0, 1.0, 1.0]
  TO_BGR255: False