MODEL:
  META_ARCHITECTURE: "DispRCNN"
  WEIGHT: "models/kitti/car/srcnn_pretrained_2d_mrcnn_format.pth"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
#    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 0
    FEATURE_EXTRACTOR: "StereoFPN2MLPFeatureExtractor"
    PREDICTOR: "StereoFPNPredictor"
    NUM_CLASSES: 2
    MLP_HEAD_DIM: 2048
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  DISPNET:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    MAX_DISP: 48
    MIN_DISP: -48
    RESOLUTIONS: (28,)
    SAMPLING_RATIO: 2
    LOSS_WEIGHT: 0.05
    CONV_LAYERS: (256,)
  MASK_ON: True
  STEREO_ON: True
  DISPNET_ON: False
DATASETS:
  TRAIN: ("kitti_train_pob_car", )
  TEST: ("kitti_train_pob_car", "kitti_val_pob_car")
DATALOADER:
  SIZE_DIVISIBILITY: 0
  NUM_WORKERS: 4
SOLVER:
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
#  when bsz*gpu=1
  BASE_LR: 0.01
  SCHEDULER: OneCycleScheduler
  MAX_ITER: 4140
  IMS_PER_BATCH: 4

  TRAIN_PSM: False
  LOAD_OPTIMIZER: False
  LOAD_SCHEDULER: False
  CHECKPOINT_PERIOD: 207
  UNCERT_LOSS_WEIGHT: 0
  GRAD_CLIP: 10.0
  PRINT_INTERVAL: 1
  DO_GRAD_CLIP: True
  FIX_BACKBONE: True
  FIX_RPN: True
  FIX_BOX_HEAD: True
  ALLOW_EXCEPTION: True
TEST:
  IMS_PER_BATCH: 4
OUTPUT_DIR:
  "models/kitti/car/pob/mask"
INPUT:
  FLIP_PROB_TRAIN: 0.0
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 10000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 10000